##########################
#miseq preprocessing
#trimusingcutadapt
dir="/home/z6/Documents/nasalmicrob/ub-ms/miseq"
out="/home/z6/Documents/nasalmicrob/ub-ms/2022/miseq"

cat sample | while read a b; do cutadapt -g GTGCCAGCMGCCGCGGTAA -G GGACTACHVGGGTWTCTAAT -o cutp-$a -p cutp-$b  --discard-untrimmed $a $b >> cutprimer.txt; done
#*All 80+% except JH19036 (75%) passed

#mergeusearch 
cat cutp-sample.txt | while read a b c; do ~/usearch11.0.667_i86linux32 -fastq_mergepairs $a -reverse $b -fastqout $c  -fastq_minlen 50 -fastq_pctid 80 --fastq_maxdiffs 10 ; done
#*All ~90% (50+k reads passed), JH19036 90% 

while read a; do ~/./usearch11.0.667_i86linux32 -fastx_truncate $a -trunclen 125 -fastqout ms-fwdtrimv4/fwd$a; done <merge


##########################
#train your dragon classifier
#Begin by downloading the relevant taxonomy and sequence files from the SILVA.
conda activate qiime2-2022.2
conda install -c conda-forge -c bioconda -c qiime2 -c defaults xmltodict
pip install git+https://github.com/bokulich-lab/RESCRIPt.git

#Import these files into QIIME 2.
qiime rescript get-silva-data \
    --p-version '138' \
    --p-target 'SSURef_NR99' \
    --p-include-species-labels \
    --o-silva-sequences silva-138-ssu-nr99-rna-seqs.qza \
    --o-silva-taxonomy silva-138-ssu-nr99-tax.qza
qiime rescript reverse-transcribe     --i-rna-sequences silva-138-ssu-nr99-rna-seqs.qza --o-dna-sequences silva-138-ssu-nr99-seqs.qza

#Remove sequences with excessive degenerate bases and homopolymers.
qiime rescript cull-seqs --i-sequences silva-138-ssu-nr99-seqs.qza --o-clean-sequences silva-138-ssu-nr99-seqs-cleaned.qza
#Remove sequences that may be too short and/or long. With the option to condition the length filtering based on taxonomy.
qiime rescript filter-seqs-length-by-taxon --i-sequences silva-138-ssu-nr99-seqs-cleaned.qza --i-taxonomy silva-138-ssu-nr99-tax.qza  \
	--p-labels Archaea Bacteria Eukaryota     --p-min-lens 900 1200 1400 \
	--o-filtered-seqs silva-138-ssu-nr99-seqs-filt.qza --o-discarded-seqs silva-138-ssu-nr99-seqs-discard.qza 
#Dereplicate the sequences and taxonomy.
qiime rescript dereplicate \
    --i-sequences silva-138-ssu-nr99-seqs-filt.qza  \
    --i-taxa silva-138-ssu-nr99-tax.qza \
    --p-rank-handles 'silva' \
    --p-mode 'uniq' \
    --o-dereplicated-sequences silva-138-ssu-nr99-seqs-derep-uniq.qza \
    --o-dereplicated-taxa silva-138-ssu-nr99-tax-derep-uniq.qza

##OPTIONAL
#Build our classifier-full length (not-extracted)
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads  silva-138-ssu-nr99-seqs-derep-uniq.qza --i-reference-taxonomy silva-138-ssu-nr99-tax-derep-uniq.qza --o-classifier silva-138-ssu-nr99-classifier.qza

#Amplicon-region specific- extract reference reads- primer for V4 trim to length 126bp
qiime feature-classifier extract-reads \
    --i-sequences silva-138-ssu-nr99-seqs-derep-uniq.qza \
    --p-f-primer GTGCCAGCMGCCGCGGTAA \
    --p-r-primer GGACTACHVGGGTWTCTAAT \
    --p-n-jobs 8 \
    --p-read-orientation 'forward' \
    --o-reads silva-138-ssu-nr99-seqs-V4.qza \
    --p-min-length 100 \
    --p-max-length 400 \
    --p-trunc-len 126 
#Dereplicate extracted region
qiime rescript dereplicate \
    --i-sequences silva-138-ssu-nr99-seqs-V4.qza \
    --i-taxa silva-138-ssu-nr99-tax-derep-uniq.qza \
    --p-rank-handles 'silva' \
    --p-mode 'uniq' \
    --o-dereplicated-sequences silva-138-ssu-nr99-seqs-V4-uniq.qza \
    --o-dereplicated-taxa  silva-138-ssu-nr99-seqs-V4-derep-uniq.qza
 #amplicon-specific classifier
 qiime feature-classifier fit-classifier-naive-bayes \
    --i-reference-reads silva-138-ssu-nr99-seqs-V4-uniq.qza \
    --i-reference-taxonomy silva-138-ssu-nr99-seqs-V4-derep-uniq.qza \
    --o-classifier silva-138-ssu-nr99-V4-classifier.qza 

 #evaluate
 qiime rescript evaluate-fit-classifier \
    --i-sequences silva-138-ssu-nr99-seqs-V4-uniq.qza \
    --i-taxonomy silva-138-ssu-nr99-seqs-V4-derep-uniq.qza  \
    --o-classifier eval-silva-138-ssu-nr99-V4-classifier.qza \
    --o-observed-taxonomy eval-silva-138-ssu-nr99-V4-predicted-taxonomy.qza \
    --o-evaluation eval-silva-138-ssu-nr99-V4-fit-classifier-evaluation.qzv 





##########################
#QIIME
conda activate qiime2-2022.2

####miseq
qiime tools import --type 'SampleData[SequencesWithQuality]' --input-path /home/z6/Documents/nasalmicrob/2022/miseq/ms-qiime/ms-manifest.txt --output-path ms-v4fwd_single-end-demux.qza --input-format SingleEndFastqManifestPhred33V2
qiime dada2 denoise-single --i-demultiplexed-seqs ms-v4fwd_single-end-demux.qza --p-trunc-len 0 --o-representative-sequences ms-v4fwd_rep-seqs.qza --o-denoising-stats ms-v4fwd_stats.qza --o-table ms-v4fwd_table.qza 
qiime feature-classifier classify-sklearn --i-reads ms-v4fwd_rep-seqs.qza --i-classifier /home/z6/Documents/nasalmicrob/2022/refdata/silva-138-ssu-nr99-V4-classifier.qza --o-classification msv4fwd_taxonomy.qza --p-n-jobs 6

####ubiome 
qiime tools import --type 'SampleData[SequencesWithQuality]' --input-path /home/z6/Documents/nasalmicrob/ubiome-nose/fwd-mf.tsv --output-path ub-v4fwd_single-end-demux.qza --input-format SingleEndFastqManifestPhred33V2
qiime dada2 denoise-single --i-demultiplexed-seqs ub-v4fwd_single-end-demux.qza --p-trunc-len 0 --o-representative-sequences ub-v4fwd_rep-seqs.qza --o-denoising-stats ub-v4fwd_stats.qza --o-table ub-v4fwd_table.qza 
qiime feature-classifier classify-sklearn --i-reads ub-v4fwd_rep-seqs.qza --i-classifier /home/z6/Documents/nasalmicrob/2022/refdata/silva-138-ssu-nr99-V4-classifier.qza --o-classification ubv4fwd_taxonomy.qza --p-n-jobs 6

##merge and filter
qiime feature-table merge --i-tables ub-v4fwd_table.qza --i-tables ms-v4fwd_table.qza --o-merged-table ubms-v4fwd_table.qza
qiime feature-table merge-seqs --i-data ub-v4fwd_rep-seqs.qza --i-data ms-v4fwd_rep-seqs.qza --o-merged-data ubms-v4fwd_rep-seqs.qza
qiime feature-table merge-taxa --i-data ubv4fwd_taxonomy.qza --i-data msv4fwd_taxonomy.qza --o-merged-data ubms-v4fwd_taxonomy.qza

qiime taxa filter-table --i-table ubms-v4fwd_table.qza --i-taxonomy ubms-v4fwd_taxonomy.qza --p-exclude mitochondria,chloroplast --o-filtered-table ubms-v4fwd-fmitochlo_table.qza
qiime taxa filter-seqs --i-sequences ubms-v4fwd_rep-seqs.qza --p-exclude mitochondria,chloroplast --i-taxonomy ubms-v4fwd_taxonomy.qza --o-filtered-sequences ubms-v4fwd-fmitochlo_rep-seqs.qza


#insertiontree
qiime fragment-insertion sepp --i-representative-sequences ubms-v4fwd-fmitochlo_rep-seqs.qza --i-reference-database refdata/sepp-refs-silva-128.qza --o-tree ubms-v4fwd_insertion-tree.qza --o-placements ubms-v4fwd_insertion-placements.qza --p-threads 8

qiime fragment-insertion filter-features   --i-table ubms-v4fwd-fmitochlo_table.qza   --i-tree ubms-v4fwd_insertion-tree.qza   --o-filtered-table ubms-v4fwd-fragins_filtered-table.qza --o-removed-table ubms-v4fwd-fragins_removed-table.qza

qiime diversity core-metrics-phylogenetic --i-phylogeny ubms-v4fwd_insertion-tree.qza --i-table ubms-v4fwd-fmitochlo_table.qza --p-sampling-depth 10000 --m-metadata-file metadata.tsv --output-dir upd_ubms-v4fwd_core-metrics-result
